### ISSUE TITLE
add Array, NonEmptyArray, List instances for At

### ISSUE THREAD

**Issue by srghma** [purescript-contrib/purescript-profunctor-lenses#125]
**Is your change request related to a problem? Please describe.**
These instances are missing - they are present in Index class, but not in At

**Comment by MonoidMusician** [comment]
There can’t be instances for these types, because you can’t insert at an arbitrary index without having all of the previous indices filled, and similarly you can’t delete an index without removing all of the later elements.

**Comment by srghma** [comment]
right, lack of sleep, tnx
