### ISSUE TITLE
Constructing a traversal where setting requires information about the current value

### ISSUE THREAD

**Issue by garyb** [purescript-contrib/purescript-profunctor-lenses#16]
I've been trying to come up with a convenient lens-based way for dealing with [`These`](https://github.com/purescript-contrib/purescript-these). I have an `Iso`, and `Prism`s for `This`, `Both`, `That`, but what would be most useful is something that allows getting/setting the "left" or "right" of a `These`, however I have no idea how to do it. Maybe it's not a law abiding construction?

The idea being, I could use `_TheseLeft` (or something) to:
- read `This a`
- read `Both a _`
- set `This a`
- update `Both a _` while setting
- take a `That b` and produce a `Both a b` while setting

I did something [a little similar in the past](https://github.com/slamdata/slamdata/blob/dc700be7287f49b73b84fc7743c064dc9521342d/src/Model/Notebook/Cell.purs#L216-L241), but that method, apart from seeming a bit dodgy in the first place, doesn't seem to translate to profunctor lenses.

Anyone out there have any ideas? @ekmett perhaps? :smile:

**Comment by zrho** [comment]
`Traversal`s for the left and right component are fine: they can not change whether a value is present and handle if there isn't one at all:

``` purescript
this :: forall a b c. Traversal (These a c) (These b c) a b
this = wander \f t -> case t of
  This a   -> This <$> f a
  That b   -> pure $ That b
  Both a b -> Both <$> f a <*> pure b

that :: forall a b c. Traversal (These a b) (These a c) b c
that = wander \f t -> case t of
  This a   -> pure $ This a
  That b   -> That <$> f b
  Both a b -> Both <$> pure a <*> f b
```

You could also use a prism:

``` purescript
_These :: forall a b c d. Prism (Tuple (Maybe a) (Maybe b)) (Tuple (Maybe c) (Maybe d)) (These a b) (These c d)
_These = prism from to where
  from (This c)                = Tuple (Just c) Nothing
  from (That d)                = Tuple Nothing (Just d)
  from (Both c d)              = Tuple (Just c) (Just d)
  to (Tuple (Just a) Nothing)  = Right (This a)
  to (Tuple Nothing (Just b))  = Right (That b)
  to (Tuple (Just a) (Just b)) = Right (Both a b)
  to _                         = Left (Tuple Nothing Nothing)
```

**Comment by garyb** [comment]
Thanks, those are both avenues I explore but neither is quite what I was after; I don't think there is an optic of the sort I was trying to make. I ended up just using `over` with a function.
