### ISSUE TITLE
Remove Index constraint from At?

### ISSUE THREAD

**Issue by pkamenarsky** [purescript-contrib/purescript-profunctor-lenses#23]
I have no idea about the theoretical foundations, but is the `Index` constraint on all `At` instances really necessary? It isn't used anywhere in the `At` instances in `profunctor-lenses` at least.

**Comment by garyb** [comment]
Dropping the constraint seems reasonable to me. Anyone know if it's required for some other reason? @paf31 / @zrho?

**Comment by zrho** [comment]
With `at` there is a canonical implementation of `ix`: `ix i = at i <<<
_Maybe`. While the constraint isn't strictly necessary, I would find it
surprising to encounter an instance of `At` that doesn't implement `Index`.
What's your motivation for removing the constraint?

**Comment by zrho** [comment]
`_Just` of course, instead of maybe.

**Comment by pkamenarsky** [comment]
It seems to me that in order to implement an `Index` instance, one has to use `wander` from the internal module `Data.Lens.Internal.Wander`. Is this the case?

**Comment by garyb** [comment]
That might well be the case. Although `Wander` is "Internal" it's not internal in the sense that it's supposed to be private to `purescript-profunctor-lenses`, it's just that it probably doesn't have much use outside of a lens context. It's totally fine to define things in terms of `wander`.

**Comment by pkamenarsky** [comment]
Oh ok, then I'm fine with defining an `Index` instance in order to fulfil the `At` constraints.
