### ISSUE TITLE
Where do we put the lenses and traversals?

### ISSUE THREAD

**Issue by zrho** [purescript-contrib/purescript-profunctor-lenses#3]
The Haskell `lens` library is infamous in the community for its dependencies and perceived heaviness, mostly because it aims to be "batteries included" and provide lenses, traversals, prisms etc. for a whole lot of libraries. This has the advantage of being incredibly convenient, because it spares us from defining the same lens each and every time we need it. However, many applications or libraries might only want to use a the core features and two or three lenses, rather than the entire bulk. Starting fresh, we have at least four options to choose from for purescript lenses:
1. Include lenses/prisms/traversals in the lens library. We would need prisms for `Either`, `Tuple`, JSON etc., some indexing type class for `Map` etc. This would pull in a whole bunch of dependencies.
2. Like the refractor library for van Laarhoven lenses - that appears pretty much dead -, we could add an
   extra library that pulls in all the dependencies and defines the lenses. This way, if one is a purist and wants to use the lens core, one can use the core library; if one wants convenience, import refractor.
3. Distribute the stuff to the package that defines the associated data type, i.e. the prisms for `Either` in `purescript-either`, the prisms for `Tuple` in purescript-tuple etc. This may need a bit of convincing of maintainers of some libraries and would add a profunctor dependency to nearly anything (maybe profunctors could be moved to the core library?). Personally, this option is my favourite.
4. Don't care. After all, user code might define _1, _Right or _Object everytime it is needed.

**Comment by paf31** [comment]
Another option: create companion libraries like `purescript-foreign-lens`. I like this as a slight variant on options 2 and 3, since I'd put "core lenses" (for things like `Tuple` and `Either` which `profunctors` necessarily depends on) in a `refractor` like package, or in the lens library itself.

**Comment by paf31** [comment]
I think this can be closed now, yes?
