### ISSUE TITLE
Add TraversableWithIndex etc.

### ISSUE THREAD

**Issue by paf31** [purescript-contrib/purescript-profunctor-lenses#37]
Now that we have functional dependencies.

**Comment by mbid** [comment]
I'd like to work on this, but wouldn't this fit better into [foldable-traversable](https://github.com/purescript/purescript-foldable-traversable)?

**Comment by paf31** [comment]
I think putting the classes there would make sense, yes, and then adding corresponding indexed traversals/folds here later.
