### ISSUE TITLE
Any interest in a ^?! function?

### ISSUE THREAD

**Issue by commandodev** [purescript-contrib/purescript-profunctor-lenses#51]
This can be quite handy (although unsafe)

```purescript
import Data.Monoid.Endo
import Partial.Unsafe

unsafeViewPrism :: forall s t a b. s -> Partial => Fold (Endo a) s t a b -> a
unsafeViewPrism s l = foldrOf l const (unsafeCrashWith "^?! empty fold") s

infixl 8 unsafeViewPrism as ^?!

```

**Comment by paf31** [comment]
I don't see why not, but maybe in a `*.Partial` module.

**Comment by commandodev** [comment]
Data.Lens.Prism.Partial or Data.Lens.Partial with all the other naughty operators?

**Comment by paf31** [comment]
Yes, the first one sounds good. Which others did you have in mind?

**Comment by commandodev** [comment]
Here you go: https://github.com/purescript-contrib/purescript-profunctor-lenses/pull/53

**Comment by MonoidMusician** [comment]
I think this can be closed since that pull request was merged
