### ISSUE TITLE
[Grate Module] Should collectOf be defined as

### ISSUE THREAD

**Issue by syaiful6** [purescript-contrib/purescript-profunctor-lenses#62]
so i played with Grate and Distributive. It look like ```collectOf``` should be defined like this:

```purescript
collectOf :: forall f s t a b. Functor f => Optic (Costar f) s t a (f a) -> (b -> s) -> f b -> t
collectOf g f = zipFWithOf g id <<< map f
```

so i can do ```collectOf cotraversed```, in psci it yield type:

```purescript
:t collectOf cotraversed
forall t1 t5 t7 t8. Functor t5 => Distributive t8 => (t1 -> t8 t7) -> t5 t1 -> t8 (t5 t7)
```

which what i want. But if i apply the current implementation to ```cotraversed``` it will yied:

```purescript
:t collectOf cotraversed
forall t5 t6 t7 t8. Distributive t8 => Distributive t5 => (t7 -> t5 t6) -> t8 t7 -> t5 (t8 t6)
```

which i believe not what we want. Notice the ```Distributive``` constraint appear both in input and output.

**Comment by syaiful6** [comment]
the ```b``` type suddenly introduced on my ```collectOf```, it look like because how this type ```f b -> a``` composed.

**Comment by paf31** [comment]
Yes, I think this is right. It took me a while to see it, but the grate in `collectOf` is currently trying to replace the wrong functor. It should be taking the place of the `Distributive` funtctor, not the other one.

Could you make a PR please?

Thanks!
