### ISSUE TITLE
Add *.Index, *.At and *.Contains

### ISSUE THREAD

**Issue by jonsterling** [purescript-contrib/purescript-profunctor-lenses#8]
I have code for this in `purescript-photons`; I'll open a PR for review.

**Comment by paf31** [comment]
:+1: Sounds good.

**Comment by paf31** [comment]
Wait, what's the difference between `At` and `Index`?

**Comment by jonsterling** [comment]
`ix` is a traversal; "setting" using this traversal will only do so if the value is already present. On the other hand, `at` is a lens to `Maybe a`, and can be used to insert or delete a value.

**Comment by paf31** [comment]
Is it an `AffineTraversal` (0 or 1 foci)?

**Comment by paf31** [comment]
Looks like it. Perhaps we can slot `AffineTraversal` into the hierarchy with something like [this](http://r6research.livejournal.com/27476.html).

**Comment by jonsterling** [comment]
It is, at least for the instances I am aware of; but I don't know if there is anything about its laws which require it to be so.
