### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by marick** [purescript-contrib/purescript-profunctor-lenses#82]
Would there be interest in API documentation containing more words and examples?

Perhaps something not to the level of http://marick.github.io/suchwow/such.better-doc.html, but definitely geared toward someone learning how to learn lenses.

More generally, the Haskell lens documentation, including the tutorial, is not well-suited to people learning lenses. It's especially difficult for someone, like me and I hope many others, not coming to PureScript from Haskell, since there are differences in organization and so on.

It would not be hard to make the PureScript lens documentation the reference standard. A fair amount of work, but not *hard* work. 

This is the sort of thing I could throw myself into, given support. I'll already (probably) be doing some of the work in https://leanpub.com/outsidefp

**Comment by garyb** [comment]
I'm not sure if you can necessarily teach people how to lens via the API docs, but yes please! I think contributions here would be greatly appreciated, I've mentioned to people for years now that it would be good to get some good (or any!) documentation in here.

**Comment by marick** [comment]
Which flavor of markdown do PureScript packages use?

**Comment by marick** [comment]
Specifically, what's the syntax for linking to, say:

```
#### `lens'`
```

in another module?

**Comment by garyb** [comment]
We don't actually have any special handling for links like that. Generally I've just been linking using a scheme that aligns with how things will generate for pursuit - so in a different module, it'd be `SomeModuleName#hash` where `#hash` would be `#v:someValue`, `#t:SomeType`, or something like that. I generally have to visit pursuit to remind myself of the value/type/etc prefixes.

**Comment by marick** [comment]
[This is doubtless the wrong forum for questions. What should I use?]

I've finished chapter 1 (lenses for product types). Then I started showing how to use lenses to traverse embedded maps, using this picture from an Elm app of mine:

![error-app-structure](https://user-images.githubusercontent.com/71909/37436997-ca6846e4-27b8-11e8-9e5b-b25d2879cd8c.png)

I couldn't figure it out. With the Elm code, it's straightforward to build a `oneAnimal` model used like this:
          Lens.update (Model.oneAnimal animalId) (Animal.addTag tag) model

But I don't see how to put an `ix` or `at` inside a composition chain. I keep getting mysterious type errors. 

Here's a starting PureScript setup: https://github.com/marick/purescript-lenses/blob/master/src/DictPath.purs

It would be enormously helpful if someone told me how to make this example as simple as it is in Elm.

**Comment by garyb** [comment]
Usually I'd say Slack, but I know you're not a fan so we can just do it in here if you like :wink:

Regarding the inferred type not working for `animalsToAnimal = at`, it's kinda a bug yeah. When you're using lenses and it says "could not match constrained type", the first step is usually to try eta-expanding the definition (adding arguments and re-applying). This does work:

``` purescript
animalsToAnimal :: String -> Lens' (Map String Animal) (Maybe Animal)
animalsToAnimal k = at k
```

Writing `modelToTag` is a bit of a problem if you want to stick only to lenses at this point, since you need to compose with a prism to make it work:

``` purescript
modelToTag id = modelToAnimals <<< animalsToAnimal id <<< _Just <<< animalToTags
```

(because `animalsToAnimal` returns a `Maybe`). The problem with that is now we're not even talking about prisms anymore, the type is:

``` purescript
modelToTag :: String -> Traversal' Model Int
```

When you compose a prism and a lens you get an "affine traversal" - although we don't have a specific type for that, because it doesn't really have any operations that differ from the standard traversal. The distinction is just that an affine traversal has 0 or 1 targets rather than 0 or many.

**Comment by garyb** [comment]
Your desired goal is easy enough with those definitions by the way:

``` purescript
updateAnimalTag model animalId tag =
  model # modelToTag animalId %~ Animal.addTag tag
```

Assuming `addTag` is some `Int -> Int -> Int` definition you had in mind. You can also write it with words if you prefer, but use of operators is much more typical with PS/Haskell lenses, in my experience. `%~` is called `over`, apparently.

If `addTag` is just going to sum the tag with the new value then there is another option too:

``` purescript
updateAnimalTag model animalId tag =
  model # modelToTag animalId +~ tag
```

**Comment by garyb** [comment]
One more comment on operators: they're ridiculed as being hard to figure out, but there's a sort of grammar to them, which can make it easier to figure out the operator you need than to remember the name of the thing that does it:

- Starts with `^`? It gets a value out of a lens by some means. `^.` for getters (where the target is known to exist - lens, iso, etc), `^?` for folds (where the target might not exist - prism, traversal, etc)
- Ends with `~`? It modifies the target. So there's `%~` where the RHS is a function to do the modification, and then `+~`, `-~`, `*~`, `<>~`, etc. which are basically aliases for things like `%~ (_ + x)`, `%~ (_ - x)`, and so on.
- Ends with `=`? Similar to `~`, but operates in a `MonadState` context.

We only have a fraction of the number of operators that you'll see in the Haskell lens library, so it does make things a little easier. The most common/important ones become second nature though, as there's only a handful: `^.` (get), `.~` (set), `%~` (modify), `^?` (get-from-fold/prism/traversal/etc).

**Comment by marick** [comment]
Thanks for indulging my luddism. 

I get this error for your solution:

```purescript
> modelToTag id = modelToAnimals <<< animalsToAnimal id <<< _Just <<< animalToTags
  Could not match type
    Record
  with type
    Maybe

while trying to match type { tags :: Int
                           }            
  with type Maybe          
              { tags :: Int
              }            
```

Perhaps relatedly, the following fails:

```purescript
> set (ix 1 <<< _Just <<< second) 8888 $ [Tuple 1 2, Tuple 3 4]
  Could not match type
    Tuple Int
  with type
    Maybe

while trying to match type Tuple Int Int
  with type Maybe (Tuple t3 Int)
while solving type class constraint
                                               
  Data.Lens.Index.Index (Array (Tuple Int Int))
                        Int                    
                        (Maybe (Tuple t3 Int)) 
```

... despite these working:

```purescript
> set (_Just <<< second) 99999 $ (Just $ Tuple 3 4)
(Just (Tuple 3 99999))

> preview (ix 1) [Tuple 1 2, Tuple 3 4]
(Just (Tuple 3 4))
```

**Comment by marick** [comment]
Darn it. I used `ix` when I meant `at`. 

It's almost as if names matter.

**Comment by marick** [comment]
However:

```purescript
> set (at 1 <<< _Just <<< second) 8888 $ [Tuple 1 2, Tuple 3 4]

  No type class instance was found for
                                           
    Data.Lens.At.At (Array (Tuple Int Int))
                    Int                    
                    (Tuple t6 Int)         
                                           
  The instance head contains unknown type variables. Consider adding a type annotation.
```

*Later*: however, since your solution does work when my mistake is corrected, I think I can defer understanding this for now.

**Comment by marick** [comment]
These comments, and ones on the purescript-beginners slack, have been really helpful. But I wonder if the "lenses for mere mortals" project would be best served with an old-fashioned mailing list, like https://groups.io/g/mere-mortal-lenses 

I keep running into problems like: 

Given, 

```purescript
ix1 :: Traversal' (Array Int) Int
ix1 = ix 1
```

... shouldn't ... Oh, darn, I think I just figured out the problem.

Anyway, a mailing list devoted to devising explanations for dummies like me would seem to be useful.

**Comment by marick** [comment]
The mailing list for explanations for dummies-like-me is https://groups.io/g/mere-mortal-lenses/topics

Re: "When you compose a prism and a lens you get an "affine traversal" - although we don't have a specific type for that, because it doesn't really have any operations that differ from the standard traversal."

In the chapter on using `ix` for maps and arrays, I've found it awkward that there's no distinct name for "the special kind of `Traversal` that `ix` produces." In a book targeting "mere mortals", I am not *not* **not** going to use "affine traversal", so I'm going to adopt scala-monocle's name and call them `Optional`.

P.S. Admittedly, my last math class was in the 1980's (ironically, I think it might have been the one on category theory -- which I dropped), but I don't see the connection to what [Wolfram MathWorld](http://mathworld.wolfram.com/Affine.html) says about "affine", much less the English language [definition](https://www.merriam-webster.com/dictionary/affine): "a relative by marriage". 

As I make pull requests about the documentation, I hope it will be OK if I convert `Data.Lens.Traveral#element`'s description from "Affine traversal the n-th focus of a Traversal" to something that shunts that sentence into the equivalent of a footnote.

**Comment by marick** [comment]
@garyb Re:

> When you compose a prism and a lens you get an "affine traversal" - although we don't have a 
> specific type for that, because it doesn't really have any operations that differ from the standard 
> traversal.

I'm having trouble explaining the difference between `ix 1 <<< at "x"` and `ix 1 <<< at "x" <<< _Just`. I think it's confusing that the type annotations for the two of them are so similar, yet one allows upsert/deletion and the other doesn't. (This is -- I think -- a distinction that Scala Monocle captures in its `Traversal` and `Optional` types. Note the composition table at https://julien-truffaut.github.io/Monocle/optics.html)

After I explained how you can use `_Just` to get rid of nested `Maybe`'s like this:

```purescript
> preview (ix 1 <<< at "x") arrayMap
(Just (Just 1))
```

I felt that the chapter needed something like this (first draft):

```
A> ### I'm confused. Why do the pipelines work so differently?
A> 
A> Our two composed optics have very similar types:
A>
A> {lang=haskell}
A> ~~~~~~~~~~~~~~
A> arrayMapX :: forall focus.
A>              Traversal' (Array (Map String focus)) (Maybe focus)
A> arrayMapX = ix 1 <<< at "x"
A> 
A> arrayMapJustX :: forall focus.
A>              Traversal' (Array (Map String focus)) focus
A> arrayMapJustX = ix 1 <<< at "x" <<< _Just
A> ~~~~~~~~~~~~~~
A>
A> ... and yet they have importantly different behaviors: the first can be
A> used to delete or add new keys, but the second cannot. Predicting whether
A> a particular type allows upsert/deletion or not is always, I think, possible, but
A> it requires a bit too much thinking for my taste. Consider this type:
A> 
A> {lang=haskell}
A> ~~~~~~~~~~~~~~
A> variant2 :: forall focus.
A>              Traversal'
A>                (Array (Map String (Maybe focus)))
A>                (Maybe focus)
A> ~~~~~~~~~~~~~~
A> 
A> Quick! Does it allow deleting a key?
A> 
A> It would be good to have type aliases to signal these distinctions to the
A> reader. Until then, I recommend looking at the actual code. 
```
