### ISSUE TITLE
Getters don't compose?

### ISSUE THREAD

**Issue by LiamGoodacre** [purescript-contrib/purescript-profunctor-lenses#85]
Oh no!

```purescript
foo :: Getter' X Y
bar :: Getter' Y Z
fooBar :: Getter' X Z
fooBar = foo <<< bar
```

```
[1/1 TypesDoNotUnify] src/Main.purs:19:18
  19  fooBar = foo <<< bar
                       ^^^

  Could not match type
    Z

  with type
    Y
```

Because `Getter` uses `Forget t` and not a constraint, it can't swap out the `t` when composing.

**Comment by LiamGoodacre** [comment]
This should work:

```purescript
class Bicontravariant p where
  bicmap :: forall a b c d. (c -> a) -> (d -> b) -> p a b -> p c d

instance bicontravariantForget :: Bicontravariant (Forget r) where
  bicmap f g (Forget m) = Forget (m <<< f)

type Getter s t a b = forall p. Strong p => Bicontravariant p => Optic p s t a b

type Getter s a = Get s s a a
```

**Comment by paf31** [comment]
I feel like there should be a simpler solution. What about just

```purescript
type Getter s t a b = forall r. Optic (Forget r) s t a b
```

**Comment by LiamGoodacre** [comment]
Yes, in fact that's exactly what I defined locally - I forgot to update the PR to do that instead!

**Comment by joshuawu** [comment]
Any progress on the PR? This issue is pretty serious IMO. It was discouraging when I ran into this problem immediately after installing this library.

**Comment by anttih** [comment]
I tried the approach @paf31 suggested. I think it works otherwise except [`takeBoth`](https://pursuit.purescript.org/packages/purescript-profunctor-lenses/4.0.0/docs/Data.Lens.Getter#v:takeBoth) doesn't compile. I'd be curious how @LiamGoodacre fixed `takeBoth`. The issue is that now `Forget r` needs to be `Forget (Tuple a c)`, which is not a `Getter`.

```
[1/1 TypesDoNotUnify] src/Data/Lens/Getter.purs:39:5

  39      cmps :: Forget a s t -> Forget c s t -> Forget (Tuple a c) s t
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  Could not match type

    Tuple a3 c4

  with type

    r0

  while trying to match type Forget (Tuple a3 c4)
    with type Forget r0
  while checking that expression (cmps (l (Forget identity))) (r (Forget identity))
    has type Forget r0 s1 t2
  in value declaration takeBoth

  where c4 is a rigid type variable
        a3 is a rigid type variable
        t2 is a rigid type variable
        s1 is a rigid type variable
        r0 is a rigid type variable
```

**Comment by LiamGoodacre** [comment]
@anttih so `Getter s t a b` is the same as a function `s -> a`, observed by [`view`](https://pursuit.purescript.org/packages/purescript-profunctor-lenses/4.0.0/docs/Data.Lens.Getter#v:view) and [`to`](https://pursuit.purescript.org/packages/purescript-profunctor-lenses/4.0.0/docs/Data.Lens.Getter#v:to).
The function `takeBoth` is just some getter noise on top of [`(&&&)`](https://pursuit.purescript.org/packages/purescript-profunctor/4.0.0/docs/Data.Profunctor.Strong#v:(&&&)).
So I switched the implementation to:
```
takeBoth :: forall s t a b c d. AGetter s t a b -> AGetter s t c d -> Getter s t (Tuple a c) (Tuple b d)
takeBoth l r = to (view l &&& view r)
```

**Comment by anttih** [comment]
Beautiful! What's `AGetter`? Also, do you want to make a PR? :)

**Comment by anttih** [comment]
Oh it's all in the PR.
