### ISSUE TITLE
Maintainer?

### ISSUE THREAD

**Issue by paf31** [purescript-contrib/purescript-profunctor-lenses#91]
I'm listed as maintainer here. Would people prefer I move this under `paf31` and actually continue to maintain it, or that we find a new maintainer?

**Comment by chexxor** [comment]
What would having it under `paf31` change? Just curious -- I don't know the differences.

**Comment by garyb** [comment]
It would mean that nobody else could merge changes / make releases, unless Phil added them as a contributor explicitly, whereas currently there are a few of us that have access.

I think contrib is a good place for this one personally - I'm not enough of a lens/profunctor expert to be able to give good feedback about new types and features, but I'm certainly capable of keeping it up to date.

**Comment by paf31** [comment]
Ok, I think we should find another maintainer then. I'll remove myself from the readme.
