### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jjl** [purescript-contrib/purescript-profunctor-lenses#92]
It would be handy to have a new release with the 0.12 support.

**Comment by justinwoo** [comment]
Have you seen https://github.com/purescript-contrib/purescript-profunctor-lenses/releases/tag/v4.0.0 ?

**Comment by jjl** [comment]
Ah, apologies, it wasn't showing up on pursuit!

**Comment by justinwoo** [comment]
It's probably worth looking into if Travis failed to publish the docs and do pulp docs --no-push to update the docs

**Comment by garyb** [comment]
It was missing the `package-lock.json` ignore and GitHub token, I've updated both so it should auto-publish in the future. About to manually push the current release to pursuit too. Thanks!
